/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYearbookRouteImport } from './routes/_authenticated/yearbook'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedQuizIndexRouteImport } from './routes/_authenticated/quiz.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedFlashcardsIndexRouteImport } from './routes/_authenticated/flashcards.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz.$quizId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedFlashcardsDeckIdRouteImport } from './routes/_authenticated/flashcards.$deckId'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin.quizzes'
import { Route as AuthenticatedAdminQuizzesQuizIdRouteImport } from './routes/_authenticated/admin.quizzes.$quizId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYearbookRoute = AuthenticatedYearbookRouteImport.update({
  id: '/yearbook',
  path: '/yearbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizIndexRoute = AuthenticatedQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlashcardsIndexRoute =
  AuthenticatedFlashcardsIndexRouteImport.update({
    id: '/flashcards/',
    path: '/flashcards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlashcardsDeckIdRoute =
  AuthenticatedFlashcardsDeckIdRouteImport.update({
    id: '/flashcards/$deckId',
    path: '/flashcards/$deckId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/admin/quizzes',
    path: '/admin/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesQuizIdRoute =
  AuthenticatedAdminQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/yearbook': typeof AuthenticatedYearbookRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/quiz/': typeof AuthenticatedQuizIndexRoute
  '/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/yearbook': typeof AuthenticatedYearbookRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/flashcards': typeof AuthenticatedFlashcardsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/quiz': typeof AuthenticatedQuizIndexRoute
  '/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/yearbook': typeof AuthenticatedYearbookRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/_authenticated/flashcards/$deckId': typeof AuthenticatedFlashcardsDeckIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/flashcards/': typeof AuthenticatedFlashcardsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/quiz/': typeof AuthenticatedQuizIndexRoute
  '/_authenticated/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/announcements'
    | '/dashboard'
    | '/events'
    | '/leaderboard'
    | '/profile'
    | '/settings'
    | '/vault'
    | '/yearbook'
    | '/admin/quizzes'
    | '/flashcards/$deckId'
    | '/groups/$groupId'
    | '/quiz/$quizId'
    | '/admin/'
    | '/flashcards/'
    | '/groups/'
    | '/quiz/'
    | '/admin/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/announcements'
    | '/dashboard'
    | '/events'
    | '/leaderboard'
    | '/profile'
    | '/settings'
    | '/vault'
    | '/yearbook'
    | '/admin/quizzes'
    | '/flashcards/$deckId'
    | '/groups/$groupId'
    | '/quiz/$quizId'
    | '/admin'
    | '/flashcards'
    | '/groups'
    | '/quiz'
    | '/admin/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/leaderboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/vault'
    | '/_authenticated/yearbook'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/flashcards/$deckId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/quiz/$quizId'
    | '/_authenticated/admin/'
    | '/_authenticated/flashcards/'
    | '/_authenticated/groups/'
    | '/_authenticated/quiz/'
    | '/_authenticated/admin/quizzes/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yearbook': {
      id: '/_authenticated/yearbook'
      path: '/yearbook'
      fullPath: '/yearbook'
      preLoaderRoute: typeof AuthenticatedYearbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/': {
      id: '/_authenticated/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof AuthenticatedQuizIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards/': {
      id: '/_authenticated/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AuthenticatedFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards/$deckId': {
      id: '/_authenticated/flashcards/$deckId'
      path: '/flashcards/$deckId'
      fullPath: '/flashcards/$deckId'
      preLoaderRoute: typeof AuthenticatedFlashcardsDeckIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes/$quizId': {
      id: '/_authenticated/admin/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
  }
}

interface AuthenticatedAdminQuizzesRouteChildren {
  AuthenticatedAdminQuizzesQuizIdRoute: typeof AuthenticatedAdminQuizzesQuizIdRoute
}

const AuthenticatedAdminQuizzesRouteChildren: AuthenticatedAdminQuizzesRouteChildren =
  {
    AuthenticatedAdminQuizzesQuizIdRoute: AuthenticatedAdminQuizzesQuizIdRoute,
  }

const AuthenticatedAdminQuizzesRouteWithChildren =
  AuthenticatedAdminQuizzesRoute._addFileChildren(
    AuthenticatedAdminQuizzesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedYearbookRoute: typeof AuthenticatedYearbookRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRouteWithChildren
  AuthenticatedFlashcardsDeckIdRoute: typeof AuthenticatedFlashcardsDeckIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedFlashcardsIndexRoute: typeof AuthenticatedFlashcardsIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedQuizIndexRoute: typeof AuthenticatedQuizIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedYearbookRoute: AuthenticatedYearbookRoute,
  AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRouteWithChildren,
  AuthenticatedFlashcardsDeckIdRoute: AuthenticatedFlashcardsDeckIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedFlashcardsIndexRoute: AuthenticatedFlashcardsIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedQuizIndexRoute: AuthenticatedQuizIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
